### ISSUE TITLE
NPE from MiniGamesBox when starting BuildBattle 5.0.2 on Paper 1.20.4.

### ISSUE THREAD

**Issue by steve4744** [Plugily-Projects/MiniGamesBox#35]
NPE starting BuildBattle 5.0.2 on Paper 1.20.4.
```
[16:59:18 ERROR]: Error occurred while enabling BuildBattle v5.0.2 (Is it up to date?)
java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-6.0.52.jar:?]
        at plugily.projects.buildbattle.minigamesbox.classic.utils.helper.ItemUtils.getSkull(ItemUtils.java:67) ~[buildbattle-5.0.2.jar:?]
        at plugily.projects.buildbattle.handlers.menu.registry.playerheads.PlayerHeadsRegistry.registerCategories(PlayerHeadsRegistry.java:65) ~[buildbattle-5.0.2.jar:?]
        at plugily.projects.buildbattle.handlers.menu.registry.playerheads.PlayerHeadsRegistry.<init>(PlayerHeadsRegistry.java:54) ~[buildbattle-5.0.2.jar:?]
        at plugily.projects.buildbattle.handlers.menu.OptionsRegistry.registerOptions(OptionsRegistry.java:79) ~[buildbattle-5.0.2.jar:?]
        at plugily.projects.buildbattle.Main.initializePluginClasses(Main.java:105) ~[buildbattle-5.0.2.jar:?]
        at plugily.projects.buildbattle.Main.onEnable(Main.java:84) ~[buildbattle-5.0.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-364]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-364]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-364]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Looks like this is caused by name being set to null on line 67 in ItemUtils#getSkull

![image](https://github.com/Plugily-Projects/MiniGamesBox/assets/6975392/5a00919d-a002-4032-b3b5-5af985e3c2e0)

**Comment by Tigerpanzer02** [comment]
True, got you covered with last commit
