### ISSUE TITLE
DeluxeMenu's GUI with Javascript expression causing some compatibility issue

### ISSUE THREAD

**Issue by izrin96** [Plugily-Projects/MiniGamesBox#62]
Hi I'm getting some issue when i'm using one of your game plugin (BuildBattle) and using DeluxeMenu GUI with Javascript expression like below:

![image](https://github.com/user-attachments/assets/40d73fb8-8cb5-42f3-83f3-f16da4de7fff)

I'm getting this error in console when trying to open my GUI i created in DeluxeMenu:

```[03:23:22 WARN]: [DeluxeMenus] Plugin DeluxeMenus v1.14.1-DEV-184 generated an exception while executing task 5884
java.lang.NoClassDefFoundError: Could not initialize class plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.internal.runtime.Context
        at buildbattle-5.0.11.jar/plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.api.scripting.NashornScriptEngine.lambda$new$0(NashornScriptEngine.java:126) ~[buildbattle-5.0.11.jar:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
        at buildbattle-5.0.11.jar/plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.api.scripting.NashornScriptEngine.<init>(NashornScriptEngine.java:124) ~[buildbattle-5.0.11.jar:?]
        at buildbattle-5.0.11.jar/plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.api.scripting.NashornScriptEngineFactory.getScriptEngine(NashornScriptEngineFactory.java:152) ~[buildbattle-5.0.11.jar:?]
        at java.scripting/javax.script.ScriptEngineManager.lambda$getEngineBy$2(ScriptEngineManager.java:237) ~[java.scripting:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397) ~[?:?]
        at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
        at java.scripting/javax.script.ScriptEngineManager.getEngineBy(ScriptEngineManager.java:246) ~[java.scripting:?]
        at java.scripting/javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:185) ~[java.scripting:?]
        at DeluxeMenus-1.14.1-DEV-184.jar/com.extendedclip.deluxemenus.requirement.JavascriptRequirement.evaluate(JavascriptRequirement.java:45) ~[DeluxeMenus-1.14.1-DEV-184.jar:?]
        at DeluxeMenus-1.14.1-DEV-184.jar/com.extendedclip.deluxemenus.requirement.RequirementList.evaluate(RequirementList.java:21) ~[DeluxeMenus-1.14.1-DEV-184.jar:?]
        at DeluxeMenus-1.14.1-DEV-184.jar/com.extendedclip.deluxemenus.menu.Menu.lambda$openMenu$10(Menu.java:372) ~[DeluxeMenus-1.14.1-DEV-184.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.1.jar:1.21.1-131-84281ce]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Craft Scheduler Thread - 12 - DeluxeMenus"]
        at buildbattle-5.0.11.jar/plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.internal.runtime.Context.lambda$static$0(Context.java:547) ~[buildbattle-5.0.11.jar:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
        at buildbattle-5.0.11.jar/plugily.projects.buildbattle.minigamesbox.classic.utils.skript.nashorn.internal.runtime.Context.<clinit>(Context.java:547) ~[buildbattle-5.0.11.jar:?]
        ... 26 more
```

Removing BuildBattle plugin fixed the issue.

**Comment by Tigerpanzer02** [comment]
Fixed
